// AI/rust-surreal-graph-rag/frontend/src/pages/Chat.tsx
import React, { useState } from 'react';
import { Stack, TextField, PrimaryButton } from '@fluentui/react';
import { chatAsk } from '@/services/chat';
import { ChatAskResponse } from '@/types/api';

const Chat: React.FC = () => {
  // 채팅 질의 상태
  const [query, setQuery] = useState('');
  const [conversationId, setConversationId] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ChatAskResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const onAsk = async () => {
    if (!query.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const res = await chatAsk({ query, conversation_id: conversationId });
      setResult(res);
      setConversationId(res.conversation_id ?? conversationId);
    } catch (e: any) {
      setError(e?.message ?? '요청 중 오류가 발생했습니다.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ padding: 16 }}>
      <Stack tokens={{ childrenGap: 12 }}>
        <h2>통합 질의응답</h2>
        <TextField
          label="질문"
          value={query}
          onChange={(_, v) => setQuery(v || '')}
          multiline
          rows={3}
        />
        <PrimaryButton onClick={onAsk} disabled={loading}>
          {loading ? '요청 중...' : '질의'}
        </PrimaryButton>

        {error && <div style={{ color: 'crimson' }}>{error}</div>}

        {result && (
          <div style={{ marginTop: 16 }}>
            <h3>답변</h3>
            <pre style={{ whiteSpace: 'pre-wrap' }}>{result.response}</pre>
            <h4>소스</h4>
            <ul>
              {result.sources.map((s, idx) => (
                <li key={idx}>
                  <strong>{s.type}</strong> - 점수: {s.score}
                  <div>{s.content}</div>
                </li>
              ))}
            </ul>
            <h4>그래프 경로</h4>
            <ul>
              {result.graph_paths.map((p, idx) => (
                <li key={idx}>{p.path}</li>
              ))}
            </ul>
            <div>
              소요 시간: {result.query_time}s, 사용 토큰: {result.tokens_used}
            </div>
          </div>
        )}
      </Stack>
    </div>
  );
};

export default Chat;

// AI/rust-surreal-graph-rag/frontend-v2/src/routes/chat/+page.svelte
<script lang="ts">
  import { chatAsk } from '$lib/services/chat';
  import type { ChatAskResponse } from '$lib/types/api';

  let query = $state('');
  let conversationId = $state<string | null>(null);
  let loading = $state(false);
  let result = $state<ChatAskResponse | null>(null);
  let error = $state<string | null>(null);

  async function onAsk() {
    if (!query.trim()) return;
    loading = true;
    error = null;
    try {
      const res = await chatAsk({ query, conversation_id: conversationId });
      result = res;
      conversationId = res.conversation_id ?? conversationId;
    } catch (e: any) {
      error = e?.message ?? '요청 중 오류가 발생했습니다.';
    } finally {
      loading = false;
    }
  }
</script>

<!-- 통합 질의응답 페이지 -->
<div class="page">
  <div class="stack">
    <h2>통합 질의응답</h2>

    <div class="field">
      <label for="query">질문</label>
      <textarea id="query" rows="3" bind:value={query}></textarea>
    </div>

    <button class="btn btn-primary" onclick={onAsk} disabled={loading}>
      {loading ? '요청 중...' : '질의'}
    </button>

    {#if error}
      <div class="error">{error}</div>
    {/if}

    {#if result}
      <div class="result">
        <h3>답변</h3>
        <pre>{result.response}</pre>

        <h4>소스</h4>
        <ul>
          {#each result.sources as s}
            <li>
              <strong>{s.type}</strong> - 점수: {s.score}
              <div>{s.content}</div>
            </li>
          {/each}
        </ul>

        <h4>그래프 경로</h4>
        <ul>
          {#each result.graph_paths as p}
            <li>{p.path}</li>
          {/each}
        </ul>

        <div>소요 시간: {result.query_time}s, 사용 토큰: {result.tokens_used}</div>
      </div>
    {/if}
  </div>
</div>

<style>
  .result {
    margin-top: 16px;
  }

  pre {
    white-space: pre-wrap;
    background: #f5f5f5;
    padding: 12px;
    border-radius: 4px;
  }
</style>
