// AI/rust-surreal-graph-rag/frontend/src/routes/health/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getHealth } from '$lib/services/health';

  let data = $state<any>(null);
  let error = $state<string | null>(null);

  onMount(async () => {
    try {
      data = await getHealth();
    } catch (e: any) {
      error = e?.message ?? '헬스 체크 실패';
    }
  });
</script>

<!-- 시스템 상태 페이지 -->
{#if error}
  <div class="page error">{error}</div>
{:else if !data}
  <div class="page">로딩 중...</div>
{:else}
  <div class="page">
    <h2>시스템 상태</h2>
    <pre>{JSON.stringify(data, null, 2)}</pre>
  </div>
{/if}

<style>
  pre {
    white-space: pre-wrap;
    background: #f5f5f5;
    padding: 12px;
    border-radius: 4px;
  }
</style>

// AI/rust-surreal-graph-rag/frontend/src/pages/Health.tsx
import React, { useEffect, useState } from 'react';
import { getHealth } from '@/services/health';

const Health: React.FC = () => {
  // 헬스 상태 조회
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    getHealth()
      .then(setData)
      .catch((e) => setError(e?.message ?? '헬스 체크 실패'));
  }, []);

  if (error) return <div style={{ padding: 16, color: 'crimson' }}>{error}</div>;
  if (!data) return <div style={{ padding: 16 }}>로딩 중...</div>;

  return (
    <div style={{ padding: 16 }}>
      <h2>시스템 상태</h2>
      <pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(data, null, 2)}</pre>
    </div>
  );
};

export default Health;
