// AI/rust-surreal-graph-rag/frontend/src/routes/login/+page.svelte
<script lang="ts">
  import { login } from '$lib/stores/auth';
  import { goto } from '$app/navigation';

  let email = $state('');
  let password = $state('');
  let loading = $state(false);
  let error = $state<string | null>(null);

  async function onSubmit() {
    loading = true;
    error = null;
    try {
      await login({ email, password });
      goto('/chat');
    } catch (e: any) {
      error = e?.message ?? '로그인에 실패했습니다.';
    } finally {
      loading = false;
    }
  }
</script>

<!-- 로그인 페이지 -->
<div class="login-container">
  <div class="stack">
    <h2>로그인</h2>

    <div class="field">
      <label for="email">이메일</label>
      <input id="email" type="text" bind:value={email} />
    </div>

    <div class="field">
      <label for="password">비밀번호</label>
      <input id="password" type="password" bind:value={password} />
    </div>

    {#if error}
      <div class="error">{error}</div>
    {/if}

    <button class="btn btn-primary" onclick={onSubmit} disabled={loading}>
      {loading ? '로그인 중...' : '로그인'}
    </button>
  </div>
</div>

<style>
  .login-container {
    max-width: 420px;
    margin: 40px auto;
    padding: 0 16px;
  }
</style>

// AI/rust-surreal-graph-rag/frontend/src/pages/Login.tsx
import React, { useState } from 'react';
import { Stack, TextField, PrimaryButton } from '@fluentui/react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/store/auth';

const Login: React.FC = () => {
  // 로그인 폼 상태
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const navigate = useNavigate();
  const { login } = useAuth();

  const onSubmit = async () => {
    setLoading(true);
    setError(null);
    try {
      await login({ email, password });
      navigate('/chat');
    } catch (e: any) {
      setError(e?.message ?? '로그인에 실패했습니다.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Stack tokens={{ childrenGap: 12 }} styles={{ root: { maxWidth: 420, margin: '40px auto' } }}>
      <h2>로그인</h2>
      <TextField label="이메일" value={email} onChange={(_, v) => setEmail(v || '')} />
      <TextField
        label="비밀번호"
        type="password"
        value={password}
        onChange={(_, v) => setPassword(v || '')}
      />
      {error && <div style={{ color: 'crimson' }}>{error}</div>}
      <PrimaryButton onClick={onSubmit} disabled={loading}>
        {loading ? '로그인 중...' : '로그인'}
      </PrimaryButton>
    </Stack>
  );
};

export default Login;
