// AI/rust-surreal-graph-rag/frontend-v2/src/routes/vector-search/+page.svelte
<script lang="ts">
  import { vectorSearch } from '$lib/services/vectorSearch';
  import type { VectorSearchResponse } from '$lib/types/api';

  let query = $state('');
  let topK = $state(5);
  let threshold = $state(0.2);
  let loading = $state(false);
  let result = $state<VectorSearchResponse | null>(null);
  let error = $state<string | null>(null);

  async function onSearch() {
    if (!query.trim()) return;
    loading = true;
    error = null;
    try {
      result = await vectorSearch({ query, top_k: topK, threshold });
    } catch (e: any) {
      error = e?.message ?? '요청 중 오류가 발생했습니다.';
    } finally {
      loading = false;
    }
  }
</script>

<!-- 벡터 검색 페이지 -->
<div class="page">
  <div class="stack">
    <h2>벡터 검색</h2>

    <div class="field">
      <label for="query">쿼리</label>
      <input id="query" type="text" bind:value={query} />
    </div>

    <div class="field">
      <label for="topk">top_k</label>
      <input id="topk" type="number" bind:value={topK} />
    </div>

    <div class="field">
      <label for="threshold">threshold</label>
      <input id="threshold" type="number" step="0.1" bind:value={threshold} />
    </div>

    <button class="btn btn-primary" onclick={onSearch} disabled={loading}>
      {loading ? '검색 중...' : '검색'}
    </button>

    {#if error}
      <div class="error">{error}</div>
    {/if}

    {#if result}
      <div class="result">
        <div>총 {result.total}건, 소요 시간: {result.query_time}s</div>
        <ul>
          {#each result.results as r}
            <li>
              <strong>{r.id}</strong> - 점수: {r.score}
              <div>{r.content}</div>
            </li>
          {/each}
        </ul>
      </div>
    {/if}
  </div>
</div>

<style>
  .result {
    margin-top: 16px;
  }
</style>

// AI/rust-surreal-graph-rag/frontend/src/pages/VectorSearch.tsx
import React, { useState } from 'react';
import { Stack, TextField, PrimaryButton } from '@fluentui/react';
import { vectorSearch } from '@/services/vectorSearch';
import { VectorSearchResponse } from '@/types/api';

const VectorSearch: React.FC = () => {
  // 벡터 검색 상태
  const [query, setQuery] = useState('');
  const [topK, setTopK] = useState<number | undefined>(5);
  const [threshold, setThreshold] = useState<number | undefined>(0.2);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<VectorSearchResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const onSearch = async () => {
    if (!query.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const res = await vectorSearch({ query, top_k: topK, threshold });
      setResult(res);
    } catch (e: any) {
      setError(e?.message ?? '요청 중 오류가 발생했습니다.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ padding: 16 }}>
      <Stack tokens={{ childrenGap: 12 }}>
        <h2>벡터 검색</h2>
        <TextField label="쿼리" value={query} onChange={(_, v) => setQuery(v || '')} />
        <TextField
          label="top_k"
          type="number"
          value={String(topK ?? '')}
          onChange={(_, v) => setTopK(v ? Number(v) : undefined)}
        />
        <TextField
          label="threshold"
          type="number"
          value={String(threshold ?? '')}
          onChange={(_, v) => setThreshold(v ? Number(v) : undefined)}
        />
        <PrimaryButton onClick={onSearch} disabled={loading}>
          {loading ? '검색 중...' : '검색'}
        </PrimaryButton>

        {error && <div style={{ color: 'crimson' }}>{error}</div>}

        {result && (
          <div style={{ marginTop: 16 }}>
            <div>
              총 {result.total}건, 소요 시간: {result.query_time}s
            </div>
            <ul>
              {result.results.map((r) => (
                <li key={r.id}>
                  <strong>{r.id}</strong> - 점수: {r.score}
                  <div>{r.content}</div>
                </li>
              ))}
            </ul>
          </div>
        )}
      </Stack>
    </div>
  );
};

export default VectorSearch;
